### ISSUE TITLE
ADT does not have all required services available

### ISSUE THREAD

**Issue by lemaiwo** [mauriciolauffer/ui5-deployer#11]
Hi Mauricio,

Thank you for the ui5-deployer! Are there any prerequisites of the system that I need to be aware of?
I'm having the following error while deploying:
info deployer:deployer Deploying project myapp
info deployer:deployer to SAP Netweaver
info deployer:deployer application myapp Connecting to http://myFioriServer:8000
ERR! deployer:deployer application myapp /sap/bc/adt/packages not found in discovery!
ERR! deployer:deployer application myapp For more information, check /sap/bc/adt/discovery
ERR! deployer:deployer Error: ADT does not have all required services available!

Any idea what goes wrong?

Thank you in advance!

Kr, Wouter

**Comment by mauriciolauffer** [comment]
@lemaiwo sorry for the ultra late response, I haven't checked the issues here for a while, sorry about that...

Newer ABAP versions have more ADT endpoints which we can use to validate all steps before sending files to the server. To avoid failing in older versions, you can use the parameter **skipAdtValidations: true** in your ui5.yaml file. Have a look at README.
