### ISSUE TITLE
Neo App deployment fails due to undefined _path

### ISSUE THREAD

**Issue by junaidhf** [mauriciolauffer/ui5-deployer#15]
Hi,
  The following code fails when we try to deploy using the npm module.
> scpui5***@0.0.1 deploy C:\***\scp-ui5-***
> ui5-deployer deploy

info normalizer:translators:ui5Framework Using SAPUI5 version: 1.85.2
info deployer:deployer Deploying project scpui5***
info deployer:deployer to SAP Cloud Platform NEO
ERR! deployer:deployer TypeError: Cannot read property '_path' of undefined
ERR! deployer:deployer     at C:\***\scp-ui5-***\node_modules\ui5-deployer\lib\types\sap-cp-neo\SapCpNeoDeployer.js:23:83
ERR! deployer:deployer     at processTicksAndRejections (internal/process/task_queues.js:93:5)
ERR! deployer:deployer     at async Object.deploy (C:\***\scp-ui5-***\node_modules\ui5-deployer\lib\deployer\deployer.js:95:7)
ERR! deployer:deployer     at async Object.handleDeploy [as handler] (C:\***\scp-ui5-***\node_modules\ui5-deployer\lib\cli\cli\commands\deployer.js:47:3)
ERR! deployer:deployer  TypeError: Cannot read property '_path' of undefined
ERR! deployer:deployer     at C:\***\scp-ui5-***\node_modules\ui5-deployer\lib\types\sap-cp-neo\SapCpNeoDeployer.js:23:83
ERR! deployer:deployer     at processTicksAndRejections (internal/process/task_queues.js:93:5)
ERR! deployer:deployer     at async Object.deploy (C:\***\scp-ui5-***\node_modules\ui5-deployer\lib\deployer\deployer.js:95:7)
ERR! deployer:deployer     at async Object.handleDeploy [as handler] (C:\***\scp-ui5-***\node_modules\ui5-deployer\lib\cli\cli\commands\deployer.js:47:3) {
ERR! deployer:deployer   stack: "TypeError: Cannot read property '_path' of undefined\n" +
ERR! deployer:deployer     '    at C:\\***\\scp-ui5-***\\node_modules\\ui5-deployer\\lib\\types\\sap-cp-neo\\SapCpNeoDeployer.js:23:83\n' +
ERR! deployer:deployer     '    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n' +
ERR! deployer:deployer     '    at async Object.deploy (C:\\***\\scp-ui5-***\\node_modules\\ui5-deployer\\lib\\deployer\\deployer.js:95:7)\n' +
ERR! deployer:deployer     '    at async Object.handleDeploy [as handler] (C:\\***\\scp-ui5-***\\node_modules\\ui5-deployer\\lib\\cli\\cli\\commands\\deployer.js:47:3)'
ERR! deployer:deployer }
ERR! deployer:deployer Deploy failed in 67 ms

⚠️  Process Failed With Error

Error Message:
Cannot read property '_path' of undefined

For details, execute the same command again with an additional '--verbose' parameter
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scpui5***@0.0.1 deploy: `ui5-deployer deploy`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scpui5***@0.0.1 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

YAML File config:
specVersion: '2.1'
metadata:
  name: ***
type: application
customConfiguration:
  deployer:
    type: sap-cp-neo
    sourcePath: /mta_archives/*.mtar  # Path to the .mtar file to be deployed
    connection:
      url: https://hana.ondemand.com
    credentials:
      username: ***
      password: ****
    sapCloudPlatform:
      neo:
        account: ****
        cliPath: C:\SAPCloudSDK\tools

Cause:
          const neoDeploy = spawn(this.buildNeoCommand(this.project, resources[0]._path), {shell: true, cwd: neoCliPath});
resources[0] -> undefined
If replaced by MTA path works fine.

**Comment by mauriciolauffer** [comment]
Thanks for the help in finding and fixing it, appreciate.
https://github.com/mauriciolauffer/ui5-deployer/pull/20
