### ISSUE TITLE
NEO deployment and environment settings

### ISSUE THREAD

**Issue by NoelHendrikx** [mauriciolauffer/ui5-deployer#16]
Hi Mauricio,

Thanks for the good work, much appreciated!

Is it possible you can add the neo: account and cliPath as a dotenv variable as well for NEO?

Thanks!

Noël

**Comment by mauriciolauffer** [comment]
Hi @NoelHendrikx

Sure thing! Gonna starting it this weekend and let you know once completed.

Thanks for the feedback   :)

**Comment by mauriciolauffer** [comment]
https://github.com/mauriciolauffer/ui5-deployer/pull/20
