### ISSUE TITLE
Error when deploying a ui5 app with a not yet created bsp container

### ISSUE THREAD

**Issue by marcelschork** [mauriciolauffer/ui5-deployer#18]
When deploying a ui5 app to SAP Netweaver and the bsp container is not yet created, I face an error (see attached screenshot). Once I create the container manually the deployment is working.

![ui5-deployer-issue](https://user-images.githubusercontent.com/63337737/107416241-8af8a100-6b14-11eb-89a7-9a3a322e0afd.png)

**Comment by mauriciolauffer** [comment]
First, it tries to find a BSP container, if it fails, it creates one.

You can see the messages confirming the creation just after the error message (404 Not Found):

- **Creating BSP Application ...**
- **Getting files from ...**
- **Calculating app index**
- **Deployed succeed in 4.01 s**

I'll improve the first error message to avoid any confusion.
