### ISSUE TITLE
TypeError: isBinaryFile is not a function

### ISSUE THREAD

**Issue by marcelschork** [mauriciolauffer/ui5-deployer#27]
Hi @mauriciolauffer,
we just recognized a type error using the latest version of the ui5-deployer for on-prem deployment.

![type_error](https://user-images.githubusercontent.com/63337737/118453548-9fda6700-b6f7-11eb-838c-6ae14826a5ea.png)

Best regards,
Marcel

**Comment by mauriciolauffer** [comment]
@marcelschork thanks for reporting. Fixed in v1.1.1
