### ISSUE TITLE
Add suport for node 12.x

### ISSUE THREAD

**Issue by sebbi08** [mauriciolauffer/ui5-deployer#30]
Hi the ui5-deployer is not working with node version 12.x due to an unsupported import statement

https://github.com/mauriciolauffer/ui5-deployer/blob/6846e23abbd04a49a8e7cf1409652edba94d45e9/lib/types/sap-netweaver/ODataClient.js#L6
https://stackoverflow.com/a/65231800

I think the support should be the same as of the ui5 tooling and this is also stated in the package.json

**Comment by mauriciolauffer** [comment]
Thanks for sharing   :)
Published on [v4.0.1](https://github.com/mauriciolauffer/ui5-deployer/releases/tag/v0.4.1).
